import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Toaster } from "sonner";
import dynamic from "next/dynamic";
// import { ThemeProvider } from "next-themes";
import { ContextProvider } from "./context/GlobalStateManager";
import NavbarDemo from "@/components/resizable-navbar-demo";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavbarDemo />
        <ContextProvider>
          {children}
          <Toaster position="bottom-center" />
        </ContextProvider>
      </body>
    </html>
  );
}
